apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
  namespace: grass-diary-backend-release
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
        - name: spring-boot-app
          image: yeseulhong/grass-diary-release:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: google-secrets
            - secretRef:
                name: jwt-secrets
            - secretRef:
                name: db-secrets
            - secretRef:
                name: s3-secrets
            - secretRef:
                name: mail-secrets
