apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: release-ingress
  namespace: grass-diary-backend-release
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - release.chzzk-diary-server.shop
    secretName: release-tls-secret
  rules:
  - host: release.chzzk-diary-server.shop
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: spring-boot-app-svc
            port: 
              number: 80
