apiVersion: v1
kind: Service
metadata:
  name: spring-boot-app-svc
  namespace: grass-diary-backend-release
spec:
  selector:
    app: spring-boot-app
  ports:
    - protocol: TCP
      name: web
      port: 80
      targetPort: 8080

